#!/bin/bash

# Vary the instruction TLB size, I-cache is 16KB, and block size is 32B
-itlb-16e.txt -tlb:itlb itlb:4:4096:4:l # Test1: Instruction TLB is 16 entries
-itlb-32e.txt -tlb:itlb itlb:8:4096:4:l # Test2: Instruction TLB is 32 entries
-itlb-128e.txt -tlb:itlb itlb:32:4096:4:l # Test3: Instruction TLB is 128 entries

# Vary the data TLB size, D-cache is 16KB, and block size is 32B
-dtlb-32e.txt -tlb:dtlb dtlb:8:4096:4:l # Test1: Data TLB is 32 entries
-dtlb-64e.txt -tlb:dtlb dtlb:16:4096:4:l # Test2: Data TLB is 64 entries
-dtlb-256e.txt -tlb:dtlb dtlb:64:4096:4:l # Test3: Data TLB is 256 entries

# Vary the page size of TLB (with TLB size fixed)
-bktlb-16.txt -tlb:itlb itlb:16:16:4:l -tlb:dtlb dtlb:32:16:4:l # Test1: Page size is 16KB
-bktlb-32.txt -tlb:itlb itlb:16:32:4:l -tlb:dtlb dtlb:32:32:4:l # Test2: Page size is 32KB
-bktlb-64.txt -tlb:itlb itlb:16:64:4:l -tlb:dtlb dtlb:32:64:4:l # Test3: Page size is 64KB
-bktlb-256.txt -tlb:itlb itlb:16:256:4:l -tlb:dtlb dtlb:32:256:4:l # Test4: Page size is 256KB

# Vary the cache replacement policy
-repl-l.txt -cache:il1 il1:512:32:1:l -cache:dl1 dl1:128:32:4:l -cache:dl2 ul2:1024:64:4:l -tlb:itlb itlb:16:4096:4:l -tlb:dtlb dtlb:32:4096:4:l # Test1: Policy is LRU
-repl-f.txt -cache:il1 il1:512:32:1:f -cache:dl1 dl1:128:32:4:f -cache:dl2 ul2:1024:64:4:f -tlb:itlb itlb:16:4096:4:f -tlb:dtlb dtlb:32:4096:4:f # Test2: Policy is FIFO
-repl-r.txt -cache:il1 il1:512:32:1:r -cache:dl1 dl1:128:32:4:r -cache:dl2 ul2:1024:64:4:r -tlb:itlb itlb:16:4096:4:r -tlb:dtlb dtlb:32:4096:4:r # Test3: Policy is RANDOM

# Compare unified cache and split cache
-cac-u.txt -cache:il1 dl1 -cache:il2 none -cache:dl1 ul1:256:32:4:l -cache:dl2 ul2:1024:64:4:l # Test1: L1 and L2 are unified
-cac-l1s.txt -cache:il1 il1:128:32:4:l -cache:dl1 dl1:128:32:4:l -cache:dl2 ul2:1024:64:4:l # Test2: L1 is split and L2 is unified
-cac-s.txt -cache:il1 il1:128:32:4:l -cache:dl1 dl1:128:32:4:l -cache:il2 il2:512:64:4:l -cache:dl2 dl2:512:64:4:l # Test1: L1 and L2 are split
